### PR TITLE
Add categories

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by disintegration** [comment]
Thank you for the contribution. The changes look great!
I'll try to review & test them this week if time allows.

**Comment by sbinet** [comment]
Great!
I apologize for the size of the PR.
But changing the store interface had quite far reaching consequences.
 
 Testing all of this in a little test instance, I realize categories could grow a 'Description' field (so this would mean another dB schema change...)

Also, I definitely lack a bit of skills on the CSS/front-end part. A few many things could be improved on the way I did implement tacking categories (and how they are displayed)...
Let me know.

**Comment by disintegration** [comment]
I've checked the code and tried these changes (with MySQL database). Some notes:

I like the simple way of displaying categories in discourse - a drop-down list with "all categories" selected by default (e.g. https://forum.golangbridge.org/latest). So you can see all the latest topics or select a specific category. Maybe we should explore this option too. What do you think?

It would be nice to have database auto-migration from older schema versions, but i'm not sure yet how to best implement it. Need to check what other projects do. I also would like to keep the postgres store in sync with mysql store.

**Comment by sbinet** [comment]
Sure :)
I started with only one of the 2 databases to limit the amount of initial work (which could have been ending up with a refused PR)

**Comment by sbinet** [comment]
wrt the "latest" "all categories", I have done something along these lines in my `improve-ui` branch.

**Comment by sbinet** [comment]
(and now, Postgres support is in)

**Comment by sbinet** [comment]
I have directed my gaze at https://github.com/go-saloon/saloon
so I don't have anymore any incentive to contribute to bebop.

feel free to reuse the code in that PR, though :)

**Comment by disintegration** [comment]
It's a nice project, wish you a good luck with it!
Maybe I will incorporate your PR code into bebop later when I have more time to work on it. Thank you!

**Pull request closed without merging**
